# Generated by Django 5.1.5 on 2025-01-22 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerChurn',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('surname', models.CharField(blank=True, max_length=50, null=True)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('geography', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('tenure', models.IntegerField(blank=True, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('num_of_products', models.IntegerField(blank=True, null=True)),
                ('has_cr_card', models.BooleanField(default=False)),
                ('is_active_member', models.BooleanField(default=False)),
                ('estimated_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('exited', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'customer_churn',
            },
        ),
        migrations.CreateModel(
            name='ChurnRiskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('churn_probability', models.FloatField()),
                ('previous_probability', models.FloatField(null=True)),
                ('risk_change', models.FloatField(null=True)),
                ('is_high_risk', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_history', to='churn_app.customerchurn')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
