# Generated by Django 5.1.5 on 2025-01-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churn_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerchurn',
            name='customer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
