# Generated by Django 5.1.5 on 2025-01-23 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churn_app', '0002_alter_customerchurn_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField(max_length=500)),
                ('is_enabled', models.BooleanField(default=True)),
                ('high_risk_threshold', models.FloatField(default=0.7)),
                ('risk_increase_threshold', models.FloatField(default=20.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('HIGH_RISK', 'High Risk'), ('RISK_INCREASE', 'Risk Increase'), ('SUMMARY', 'Monitoring Summary')], max_length=20)),
                ('message', models.JSONField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('was_sent', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='churn_app.customerchurn')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
