# Use official Python image as base
FROM python:3.12

# Set working directory
WORKDIR /app

# Copy requirements
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the entire Django project
COPY . .

# Expose the Django dev server port
EXPOSE 8000

# Run migrations + start server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
