version: '3.8'
services:
  migrations:
    build: .
    container_name: churn_migrations
    command: sh -c "python manage.py makemigrations && python manage.py migrate"
    volumes:
      - .:/app
    depends_on:
      - db

  createadmin:
    build: .
    container_name: churn_createadmin
    command: sh -c "echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('root', 'admin@example.com', 'root') if not User.objects.filter(username='root').exists() else None\" | python manage.py shell"
    volumes:
      - .:/app
    depends_on:
      - db
      - migrations

  frontend:
    build:
      context: ../churn-prediction-frontend
      dockerfile: Dockerfile
    container_name: churn_frontend
    ports:
      - "3000:3000"
    depends_on:
      - web
      - createadmin
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000

  web:
    build: .
    container_name: churn_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - createadmin
      - migrations

  celery:
    build: .
    container_name: churn_celery
    command: celery -A churn_project worker -l info --pool=solo
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    container_name: churn_celery_beat
    command: celery -A churn_project beat -l info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    container_name: churn_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: churn_db
    ports:
      - "5439:5432"
    # volumes:
      # Mount the init folder containing .sql scripts and the CSV
      # - ./init:/docker-entrypoint-initdb.d

  redis:
    image: redis:latest
    container_name: churn_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
